baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My talks'
author = "ButbkaDrug"
copyright = "ButbkaDrug"
pagination.pagerSize = 10
theme = "tailwind"

[module]
  [[module.imports]]
    path = "github.com/tomowang/hugo-theme-tailwind"

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "logo.png"

  [params.footer]
    since = 2023
    poweredby = true
