baseURL = 'http://example.org/'
languageCode = 'ru-ru'
title = 'Butbka World'
theme = 'hugo-coder'

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
    style = "dracula"
    lineNos = true

[params]
  author = "Viktar Ivanou"
  info = "Welcome! Join me in exploring my observations and insights. This space is dedicated to sharing thoughts and reflections from my personal journey."
  description = "My personal page for all kinds of things"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "butbkadrug@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/butbkadrug/"
[[params.social]]
  name = "Buy me a coffee"
  icon = "fa fa-buymeacoffee fa-2x"
  weight = 3
  url = "https://www.buymeacoffee.com/butbkadruge"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 2
  url = "https://t.me/butbkadrug"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
